vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#89b4fa" })
vim.api.nvim_set_hl(0, "@function", { fg = "#89b4fa" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#a6e3a1" })
vim.api.nvim_set_hl(0, "@variable.member", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@keyword.return", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@keyword.loop", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@keyword.repeat", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@keyword.conditional", { fg = "#f38ba8" })
vim.api.nvim_set_hl(0, "@number", { fg = "#cba6f7" })
vim.api.nvim_set_hl(0, "@string", { fg = "#f9e2af" })

vim.keymap.set("n", "<C-e>", function()
	local result = vim.treesitter.get_captures_at_cursor(0)
	print(vim.inspect(result))
end)
